[package]
name             = "deposit_circuit"
type             = "bin"                   # stays "bin" for an executable circuit
compiler_version = "1.0.0"                 # whatever youâ€™re on
# add or change this line:
entry            = "src/deposit.nr"
[dependencies]